/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPatternsRouteImport } from './routes/_authenticated/patterns'
import { Route as AuthenticatedMonthRouteImport } from './routes/_authenticated/month'
import { Route as AuthenticatedDiaryRouteImport } from './routes/_authenticated/diary'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatternsRoute = AuthenticatedPatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonthRoute = AuthenticatedMonthRouteImport.update({
  id: '/month',
  path: '/month',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiaryRoute = AuthenticatedDiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/diary': typeof AuthenticatedDiaryRoute
  '/month': typeof AuthenticatedMonthRoute
  '/patterns': typeof AuthenticatedPatternsRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/diary': typeof AuthenticatedDiaryRoute
  '/month': typeof AuthenticatedMonthRoute
  '/patterns': typeof AuthenticatedPatternsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/diary': typeof AuthenticatedDiaryRoute
  '/_authenticated/month': typeof AuthenticatedMonthRoute
  '/_authenticated/patterns': typeof AuthenticatedPatternsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/diary' | '/month' | '/patterns'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/diary' | '/month' | '/patterns' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/diary'
    | '/_authenticated/month'
    | '/_authenticated/patterns'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patterns': {
      id: '/_authenticated/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof AuthenticatedPatternsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/month': {
      id: '/_authenticated/month'
      path: '/month'
      fullPath: '/month'
      preLoaderRoute: typeof AuthenticatedMonthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diary': {
      id: '/_authenticated/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof AuthenticatedDiaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDiaryRoute: typeof AuthenticatedDiaryRoute
  AuthenticatedMonthRoute: typeof AuthenticatedMonthRoute
  AuthenticatedPatternsRoute: typeof AuthenticatedPatternsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDiaryRoute: AuthenticatedDiaryRoute,
  AuthenticatedMonthRoute: AuthenticatedMonthRoute,
  AuthenticatedPatternsRoute: AuthenticatedPatternsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
