// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txrxzsrjqwhvjosutotp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4cnh6c3JqcXdodmpvc3V0b3RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIzODgyMTYsImV4cCI6MjA5Nzk2NDIxNn0.zC8p5VqJqWGWqX2KG_R78fwnPmdy6ui6WwmoAfFc6oc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== "undefined" ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});